/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author Supun
 */
public class Calculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    /**
     * Creates new form Calculator
     */
    double numEnter1;
    double numEnter2;
    double result;
    double lastNumber = 0;
    boolean repeatEqual = false;
    String op;
    public Calculator() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnCE = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDigit8 = new javax.swing.JButton();
        jbtnDigit7 = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnDigit9 = new javax.swing.JButton();
        jbtnDigit5 = new javax.swing.JButton();
        jbtnDigit4 = new javax.swing.JButton();
        jbtnMinous = new javax.swing.JButton();
        jbtnDigit6 = new javax.swing.JButton();
        jbtnDigit2 = new javax.swing.JButton();
        jbtnDigit1 = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnDigit3 = new javax.swing.JButton();
        jbtnPoint = new javax.swing.JButton();
        jbtnDigit0 = new javax.swing.JButton();
        jbtnDevision = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setBackground(new java.awt.Color(248, 255, 236));
        jtxtResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 110));

        jbtnCE.setBackground(new java.awt.Color(255, 204, 255));
        jbtnCE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCE.addActionListener(this::jbtnCEActionPerformed);
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, 70));

        jbtnBS.setBackground(new java.awt.Color(200, 250, 243));
        jbtnBS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnBS.setText("←");
        jbtnBS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBS.addActionListener(this::jbtnBSActionPerformed);
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 70));

        jbtnPM.setBackground(new java.awt.Color(200, 250, 243));
        jbtnPM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPM.setText("±");
        jbtnPM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPM.addActionListener(this::jbtnPMActionPerformed);
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 70, 70));

        jbtnC.setBackground(new java.awt.Color(255, 204, 255));
        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnC.addActionListener(this::jbtnCActionPerformed);
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, 70));

        jbtnDigit8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit8.setText("8");
        jbtnDigit8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit8.addActionListener(this::jbtnDigit8ActionPerformed);
        getContentPane().add(jbtnDigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 70));

        jbtnDigit7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit7.setText("7");
        jbtnDigit7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit7.addActionListener(this::jbtnDigit7ActionPerformed);
        getContentPane().add(jbtnDigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 70));

        jbtnPlus.setBackground(new java.awt.Color(200, 250, 243));
        jbtnPlus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPlus.addActionListener(this::jbtnPlusActionPerformed);
        getContentPane().add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 70));

        jbtnDigit9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit9.setText("9");
        jbtnDigit9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit9.addActionListener(this::jbtnDigit9ActionPerformed);
        getContentPane().add(jbtnDigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 70, 70));

        jbtnDigit5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit5.setText("5");
        jbtnDigit5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit5.addActionListener(this::jbtnDigit5ActionPerformed);
        getContentPane().add(jbtnDigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 70, 70));

        jbtnDigit4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit4.setText("4");
        jbtnDigit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit4.addActionListener(this::jbtnDigit4ActionPerformed);
        getContentPane().add(jbtnDigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 70, 70));

        jbtnMinous.setBackground(new java.awt.Color(200, 250, 243));
        jbtnMinous.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnMinous.setText("-");
        jbtnMinous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMinous.addActionListener(this::jbtnMinousActionPerformed);
        getContentPane().add(jbtnMinous, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 70, 70));

        jbtnDigit6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit6.setText("6");
        jbtnDigit6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit6.addActionListener(this::jbtnDigit6ActionPerformed);
        getContentPane().add(jbtnDigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 70, 70));

        jbtnDigit2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit2.setText("2");
        jbtnDigit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit2.addActionListener(this::jbtnDigit2ActionPerformed);
        getContentPane().add(jbtnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, 70));

        jbtnDigit1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit1.setText("1");
        jbtnDigit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit1.addActionListener(this::jbtnDigit1ActionPerformed);
        getContentPane().add(jbtnDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 70, 70));

        jbtnMulti.setBackground(new java.awt.Color(200, 250, 243));
        jbtnMulti.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnMulti.setText("*");
        jbtnMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMulti.addActionListener(this::jbtnMultiActionPerformed);
        getContentPane().add(jbtnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 70, 70));

        jbtnDigit3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit3.setText("3");
        jbtnDigit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit3.addActionListener(this::jbtnDigit3ActionPerformed);
        getContentPane().add(jbtnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 70, 70));

        jbtnPoint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPoint.setText(".");
        jbtnPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPoint.addActionListener(this::jbtnPointActionPerformed);
        getContentPane().add(jbtnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 70, 70));

        jbtnDigit0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDigit0.setText("0");
        jbtnDigit0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDigit0.addActionListener(this::jbtnDigit0ActionPerformed);
        getContentPane().add(jbtnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 70, 70));

        jbtnDevision.setBackground(new java.awt.Color(200, 250, 243));
        jbtnDevision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDevision.setText("/");
        jbtnDevision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDevision.addActionListener(this::jbtnDevisionActionPerformed);
        getContentPane().add(jbtnDevision, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 70, 70));

        jbtnEqual.setBackground(new java.awt.Color(102, 153, 255));
        jbtnEqual.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnEqual.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEqual.setText("=");
        jbtnEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEqual.addActionListener(this::jbtnEqualActionPerformed);
        getContentPane().add(jbtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit7ActionPerformed
       EnterNumbers("7");
    }//GEN-LAST:event_jbtnDigit7ActionPerformed

    private void jbtnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtnDigit8ActionPerformed

    private void jbtnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtnDigit9ActionPerformed

    private void jbtnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtnDigit4ActionPerformed

    private void jbtnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtnDigit5ActionPerformed

    private void jbtnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtnDigit6ActionPerformed

    private void jbtnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtnDigit1ActionPerformed

    private void jbtnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtnDigit2ActionPerformed

    private void jbtnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtnDigit3ActionPerformed

    private void jbtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtnDigit0ActionPerformed

    private void jbtnDevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDevisionActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        op= "/";
        jtxtResult.setText("");
        
        repeatEqual = false;
        repeatEqual = false;
        repeatEqual = false;
        repeatEqual = false;
    }//GEN-LAST:event_jbtnDevisionActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        repeatEqual = false;
        repeatEqual = false;
        op= "*";
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnMinousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinousActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        op= "-";
        jtxtResult.setText("");
        
        repeatEqual = false;
        repeatEqual = false;
    }//GEN-LAST:event_jbtnMinousActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        op= "+";
        jtxtResult.setText("");
        
        repeatEqual = false;
        repeatEqual = false;
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
        repeatEqual = false;
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");
        
        String fn, sn;
        fn = String.valueOf(numEnter1);
        sn = String.valueOf(numEnter2);
        
        fn="";
        sn="";
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        nums = nums * (-1);
        jtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        String backSpace = null;
        
        if(jtxtResult.getText().length()>0){
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length()-1);
            backSpace =sb.toString();
            jtxtResult.setText(backSpace);
        }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPointActionPerformed
        if (! jtxtResult.getText().contains(".") )
        {
            jtxtResult.setText(jtxtResult.getText() + jbtnPoint.getText());
        }
    }//GEN-LAST:event_jbtnPointActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed

        if (!repeatEqual) {
            numEnter2 = Double.parseDouble(jtxtResult.getText());
            lastNumber = numEnter2;
        } else {
            numEnter1 = result;
            numEnter2 = lastNumber;
        }

        if (op.equals("+")) {
            result = numEnter1 + numEnter2;
        } else if (op.equals("-")) {
            result = numEnter1 - numEnter2;
        } else if (op.equals("*")) {
            result = numEnter1 * numEnter2;
        } else if (op.equals("/")) {
            result = numEnter1 / numEnter2;
        }

        if (result == (long) result) {
            jtxtResult.setText(String.valueOf((long) result));
        } else {
            jtxtResult.setText(String.valueOf(result));
        }

        numEnter1 = result;
        repeatEqual = true;
    }//GEN-LAST:event_jbtnEqualActionPerformed
    private void EnterNumbers (String q){
        String Nums =jtxtResult.getText() +q;
        jtxtResult.setText(Nums);
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDevision;
    private javax.swing.JButton jbtnDigit0;
    private javax.swing.JButton jbtnDigit1;
    private javax.swing.JButton jbtnDigit2;
    private javax.swing.JButton jbtnDigit3;
    private javax.swing.JButton jbtnDigit4;
    private javax.swing.JButton jbtnDigit5;
    private javax.swing.JButton jbtnDigit6;
    private javax.swing.JButton jbtnDigit7;
    private javax.swing.JButton jbtnDigit8;
    private javax.swing.JButton jbtnDigit9;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnMinous;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnPoint;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
